spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
  h2:
    console:
      enabled: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

